---
env:
    browser: true
    es2020: true
    es6: true
    node: true
    jest: true

extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:@typescript-eslint/recommended
    - prettier
    - plugin:i18next/recommended

parser: '@typescript-eslint/parser'

parserOptions:
    ecmaVersion: 2020
    sourceType: module
    ecmaFeatures:
        jsx: true

plugins:
    - react
    - react-hooks
    - '@typescript-eslint'
    - i18next
    - eslint-plugin-jsonc

rules:
    # ESLint rules

    # no-console: 2

    # Require a whitespace at the beginning of a comment
    spaced-comment:
        - error
        - always

    # Maximum line length for comments except trailing comments
    max-len:
        - error
        - comments: 120
          code: 200 # Set to not conflict with Prettier
          ignoreTrailingComments: true
          ignoreTemplateLiterals: true
          ignoreUrls: true

    # Require braces around blocks
    curly:
        - error
        - all

    # Require parentheses around arrow function arguments
    arrow-parens:
        - error
        - always

    # Require blank line before certain statements
    padding-line-between-statements:
        - error
        - blankLine: always
          prev: '*'
          next: function
        - blankLine: always
          prev: '*'
          next: class
        - blankLine: always
          prev: '*'
          next: export
        # Ignore consecutive export statements
        - blankLine: any
          prev: export
          next: export
        - blankLine: always
          prev: '*'
          next: return
        - blankLine: always
          prev: '*'
          next: break
        - blankLine: always
          prev: '*'
          next: continue
        - blankLine: always
          prev: '*'
          next: throw

    # eslint-plugin-react rules

    # Require props to be sorted
    react/jsx-sort-props:
        - error
        - callbacksLast: true
          shorthandFirst: true

    # Omit boolean prop value when set to true
    react/jsx-boolean-value:
        - error
        - never

    # Require self closing tags in JSX/HTML
    react/self-closing-comp:
        - error
        - component: true
          html: true

    # Require PascalCase for user-defined JSX components
    react/jsx-pascal-case:
        - error

    react/prop-types:
        - off

    # Disallow unnecessary curly braces in JSX
    react/jsx-curly-brace-presence:
        - error
        - never

    # React in jsx scope
    react/react-in-jsx-scope:
        - off

    # eslint-plugin-react-hooks rules

    # Enforce rules of hooks
    react-hooks/rules-of-hooks: error

    # eslint-plugin-jsonc rules

    # Require keys to be sorted
    jsonc/sort-keys:
        - error
        - pathPattern: '.*'
          order:
              type: asc

    # @typescript-eslint rules

    # Require explicit return type on functions and class methods
    '@typescript-eslint/explicit-function-return-type':
        - off

    # disable the rule for all files
    '@typescript-eslint/explicit-module-boundary-types':
        - off

    '@typescript-eslint/no-use-before-define': warn

    '@typescript-eslint/no-var-requires': off

    # React rules

    react/display-name:
        - off

    # React rules

    # i18next rules

    i18next/no-literal-string: error

overrides:
    # eslint-plugin-jsonc requires its own parser
    - files:
          - '*.json'
      parser: jsonc-eslint-parser
      rules:
          eol-last:
              - off

    # Certain rules not required for JSON files
    - files:
          - '*.json'
      rules:
          max-len:
              - off
          jsonc/sort-keys:
              - off
    - files:
          - src/locale/**/*.json
      rules:
          jsonc/sort-keys:
              - error

    # i18next rule is not required for js, jsx, json and test file
    - files:
          - src/**/*.{js,jsx,json}
          - src/**/*.test.{tsx,ts}
          - src/**/*.mock.{tsx,ts}
      rules:
          i18next/no-literal-string:
              - off

    # i18next rule is not required for js, jsx, json and test file
    - files:
          - src/**/*.{js,jsx,json}
          - src/**/*.test.{tsx,ts}
          - src/**/*.mock.{tsx,ts}
      rules:
          i18next/no-literal-string:
              - off

settings:
    react:
        version: detect
