const HTTP_STATUS_CODE = {
    BAD_REQUEST: 400,
    CONFLICT: 409,
    UNAUTHORISED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    SUCCESS: 200,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
};

const ROLES = {
    SUPER_ADMIN_ROLE: 1,
    ADMIN_ROLE: 2,
};

module.exports = {
    HTTP_STATUS_CODE,
    ROLES,
};
