const HTTP_STATUS_CODE = {
    BAD_REQUEST: 400,
    CONFLICT: 409,
    UN_AUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    SUCCESS: 200,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
};

module.exports = {
    HTTP_STATUS_CODE,
};
